kind: pipeline
type: exec
name: corona-rules

platform:
  os: linux

steps:
  - name: stop-current
    commands:
      - docker-compose down

  - name: build-frontend
    commands:
      - cd frontend
      - npm run build

  - name: start
    commands:
      - docker-compose up -d