kind: pipeline
type: docker
name: corona-rules

platform:
  os: linux

steps:
  - name: build-frontend
    image: node:alpine
    commands:
      - cd frontend
      - npm install
      - npm run build

  - name: execute
    image: docker/compose:1.27.4
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose down
      - docker-compose up --build -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main