kind: pipeline
type: docker
name: corona-rules

platform:
  os: linux

steps:
  - name: build-frontend
    image: node:alpine
    commands:
      - cd frontend
      - npm install
      - npm run build

  - name: build-go
    image: golang
    commands:
      - go get
      - go build

  - name: run
    image: golang
    commands:
      - ./main